version: 1.0.{build}

branches:
  # whitelist
  only:
    - master

init:
  - ps: wget https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1
  - ps: .\dotnet-install.ps1 -Version 2.1.300

skip_tags: true

image: Visual Studio 2017
shallow_clone: true
clone_depth: 1

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CERTES_ACME_ACCOUNT_KEY:
    secure: fmkn8cbE+A1dHITS3s7NADqKi+2rYNKSSjuuLWvkX199WThoEptlCXKAwxlMhWZtBrXdNU5D+1RHI2ouDwWF7hwcIHcGf30v2UohFR+YHujT/N6c4EnK3261CNNm6AklbINPJ72+QPu04/NqEzDAtA==
  CERTES_AZURE_SUBSCRIPTION_ID:
    secure: FSK01SfyZI0x6AX2XVDxcE6kUAmg4fYja2hsNcQNBxa1PBddSZtZ8rthvO5c8o/R
  CERTES_AZURE_TENANT_ID:
    secure: 4FrR9+ARA8H+bLFFQDT4C1TAZv/LTO69vFpfjpqR5BVTedqgsZcey6xuS2TDA46l
  CERTES_AZURE_CLIENT_ID:
    secure: icfPnryDWgqU1TmP3J7gsidrpY9jGAuWY4gXf6CeDkVOELNN25JaeMvaRztUqtlb
  CERTES_AZURE_CLIENT_SECRET:
    secure: igTLkiccsMP8ctXsHH6ymG8CKv6dXbi0HUqjcqyjfAZcgJp5NtDWH/7Ch0FVw9gt

cache:

install:

nuget:
  disable_publish_on_pr: false

build_script:
  - ps: cd ./src/Certes.Spa
  - ps: npm install
  - ps: npm run build
  - ps: cd $env:APPVEYOR_BUILD_FOLDER

test: off

artifacts:
  - path: './src/Certes.Spa/build/**/*.*'
    name: spa

deploy:
