version: 1.0.{build}

branches:
  # whitelist
  only:
    - master

init:

skip_tags: true

image: Visual Studio 2017
shallow_clone: true
clone_depth: 1

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CERTES_AZURE_SUBSCRIPTION_ID:
    secure: FSK01SfyZI0x6AX2XVDxcE6kUAmg4fYja2hsNcQNBxa1PBddSZtZ8rthvO5c8o/R
  CERTES_AZURE_TENANT_ID:
    secure: 4FrR9+ARA8H+bLFFQDT4C1TAZv/LTO69vFpfjpqR5BVTedqgsZcey6xuS2TDA46l
  CERTES_AZURE_CLIENT_ID:
    secure: icfPnryDWgqU1TmP3J7gsidrpY9jGAuWY4gXf6CeDkVOELNN25JaeMvaRztUqtlb
  CERTES_AZURE_CLIENT_SECRET:
    secure: igTLkiccsMP8ctXsHH6ymG8CKv6dXbi0HUqjcqyjfAZcgJp5NtDWH/7Ch0FVw9gt
  AZURE_STORAGE_ACCOUNT: certesapp
  AZURE_STORAGE_KEY:
    secure: uz/DFUHwg8NbiuV2+T/tLpzfs8JCsl52oskYtTpzt1vTfa2A2ZGcHxQsiCvwi31uhfW3yLeG/6izbq/xqu/OeZ1tRUbsfZ4G7MLBKOgYF2h+B8BhiCtrGxFKVLN8/EMa

cache:

install:
  - ps: wget https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1
  - ps: .\dotnet-install.ps1 -Version 2.1.300
  - ps: Install-Product node ''

nuget:
  disable_publish_on_pr: false

build_script:
  - cd ./src/Certes.Spa
  - npm install
  - npm run build
  - ps: cd $env:APPVEYOR_BUILD_FOLDER
  - ps: az storage blob upload-batch -d spa -s ./src/Certes.Spa/build/ --account-name "$($env:AZURE_STORAGE_ACCOUNT)" --account-key "$($env:AZURE_STORAGE_KEY)"

test: off
