version: 1.0.{build}

branches:
  # whitelist
  only:
    - master

init:

skip_tags: true

image: Visual Studio 2017
shallow_clone: true
clone_depth: 1

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CERTES_ACME_ACCOUNT_KEY:
    secure: fmkn8cbE+A1dHITS3s7NADqKi+2rYNKSSjuuLWvkX199WThoEptlCXKAwxlMhWZtBrXdNU5D+1RHI2ouDwWF7hwcIHcGf30v2UohFR+YHujT/N6c4EnK3261CNNm6AklbINPJ72+QPu04/NqEzDAtA==
  CERTES_AZURE_SUBSCRIPTION_ID:
    secure: u2ucwWE9SyLLf4RRaNioPpgoqHf9vIwY+kgtbTmf8vKXIKZIPaLOFDC8gH7rZd06
  CERTES_AZURE_TENANT_ID:
    secure: 4FrR9+ARA8H+bLFFQDT4C1TAZv/LTO69vFpfjpqR5BVTedqgsZcey6xuS2TDA46l
  CERTES_AZURE_CLIENT_ID:
    secure: dp7MAPn/z/amC3/+IpVOdDtXESia2b/kgMj4DlzgmJfiWVewj1VFHQjBr6KO2cTZ
  CERTES_AZURE_CLIENT_SECRET:
    secure: vauTaR2HBmDtUeuWbKncWqJlbkqjE0kdvxOvl0VfbMBnZIBA+bhgQvgdErBFZ8/H
  AZURE_STORAGE_ACCOUNT: certesapp
  AZURE_STORAGE_KEY:
    secure: uz/DFUHwg8NbiuV2+T/tLpzfs8JCsl52oskYtTpzt1vTfa2A2ZGcHxQsiCvwi31uhfW3yLeG/6izbq/xqu/OeZ1tRUbsfZ4G7MLBKOgYF2h+B8BhiCtrGxFKVLN8/EMa

cache:

install:
  - ps: wget https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1
  - ps: .\dotnet-install.ps1 -Version 2.1.300 -InstallDir ./dotnet2.1
  - ps: Install-Product node ''

nuget:
  disable_publish_on_pr: false

build_script:
  - dotnet tool install --global dotnet-certes
  - ps: $env:DOTNET_ROOT = "$($env:APPVEYOR_BUILD_FOLDER)\dotnet2.1"
  - ps: $env:Path += ";$($env:USERPROFILE)\.dotnet\tools\"
  - ps: $san = "ci-$($env:APPVEYOR_BUILD_NUMBER).certes.app"
  - ps: $order = certes order new www.certes.app $san | ConvertFrom-Json
  - ps: Add-AppveyorMessage -Message $order.location
  - ps: certes az dns $order.location www.certes.app --resource-group certes
  - ps: certes az dns $order.location $san --resource-group certes
  - ps: certes order validate $order.location www.certes.app dns
  - ps: certes order validate $order.location $san dns
  - ps: certes order finalize $order.location --dn "CN=www.certes.app" --out ./key.pem
  - ps: certes az app $order.location www.certes.app certes-app --resource-group certes --private-key ./key.pem
  - cd ./src/Certes.Spa
  - npm install
  - npm run build
  - ps: cd $env:APPVEYOR_BUILD_FOLDER
  - az storage blob upload-batch -d spa -s ./src/Certes.Spa/build/ --no-progress

test: off
