version: 1.0.0.{build}

branches:
  # whitelist
  only:
    - master

init:

skip_tags: true

image: Visual Studio 2017
shallow_clone: true
clone_depth: 1

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CERTES_ACME_ACCOUNT_KEY:
    secure: fmkn8cbE+A1dHITS3s7NADqKi+2rYNKSSjuuLWvkX199WThoEptlCXKAwxlMhWZtBrXdNU5D+1RHI2ouDwWF7hwcIHcGf30v2UohFR+YHujT/N6c4EnK3261CNNm6AklbINPJ72+QPu04/NqEzDAtA==
  CERTES_AZURE_SUBSCRIPTION_ID:
    secure: u2ucwWE9SyLLf4RRaNioPpgoqHf9vIwY+kgtbTmf8vKXIKZIPaLOFDC8gH7rZd06
  CERTES_AZURE_TENANT_ID:
    secure: 4FrR9+ARA8H+bLFFQDT4C1TAZv/LTO69vFpfjpqR5BVTedqgsZcey6xuS2TDA46l
  CERTES_AZURE_CLIENT_ID:
    secure: dp7MAPn/z/amC3/+IpVOdDtXESia2b/kgMj4DlzgmJfiWVewj1VFHQjBr6KO2cTZ
  CERTES_AZURE_CLIENT_SECRET:
    secure: vauTaR2HBmDtUeuWbKncWqJlbkqjE0kdvxOvl0VfbMBnZIBA+bhgQvgdErBFZ8/H
  AZURE_STORAGE_ACCOUNT: certesapp
  AZURE_STORAGE_KEY:
    secure: uz/DFUHwg8NbiuV2+T/tLpzfs8JCsl52oskYtTpzt1vTfa2A2ZGcHxQsiCvwi31uhfW3yLeG/6izbq/xqu/OeZ1tRUbsfZ4G7MLBKOgYF2h+B8BhiCtrGxFKVLN8/EMa
  MSDEPLOY_CERTES_APP_PWD:
    secure: qZR34x3SpE/pc5EwpgxjrfpEauJ6I+peFm5ubYwy9u5ESdUjcyaQXHzX1cyjDQK5JUZOX5tS6GAYG214huB22g==
  MSDEPLOY_CERTES_API_PWD:
    secure: T2FghxRhn/rE3vWkzq/ACu7CfuYGIa45tBJ8D/LrJ2ZKnY1naPAMz7EwXa5qgRlGgh/gSR9M5qfYDqGVwx2/kQ==
  REACT_APP_API_ROOT: https://api.certes.app

cache:

install:
  - ps: wget https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1
  - ps: .\dotnet-install.ps1 -Version 2.1.300 -InstallDir ./dotnet2.1
  - ps: Install-Product node ''
  - az login --service-principal -u %CERTES_AZURE_CLIENT_ID% -p %CERTES_AZURE_CLIENT_SECRET% --tenant %CERTES_AZURE_TENANT_ID% > nul
  - az account set --subscription %CERTES_AZURE_SUBSCRIPTION_ID% > nul

nuget:
  disable_publish_on_pr: true

build_script:
  # fix dotnet path
  - ps: $env:DOTNET_ROOT = "$($env:APPVEYOR_BUILD_FOLDER)\dotnet2.1"
  - ps: $env:Path += ";$($env:USERPROFILE)\.dotnet\tools\"
  # renew SSL
  - dotnet tool install --global dotnet-certes
  - ps: $nonce = "ci-$($env:APPVEYOR_BUILD_NUMBER % 10).certes.app"
  - ps: $order = certes order new *.certes.app api.certes.app $nonce | ConvertFrom-Json
  - ps: Add-AppveyorMessage -Message $order.location
  - ps: certes az dns $order.location *.certes.app --resource-group certes | Out-Null
  - ps: certes az dns $order.location $nonce --resource-group certes | Out-Null
  - ps: certes order validate $order.location *.certes.app dns | Out-Null
  - ps: certes order validate $order.location $nonce dns | Out-Null
  - ps: certes order finalize $order.location --dn "CN=*.certes.app" --out ./key.pem | Out-Null
  - ps: certes az app $order.location *.certes.app certes-app --resource-group certes --private-key ./key.pem | Out-Null
  - ps: certes az app $order.location *.certes.app certes-api --resource-group certes --private-key ./key.pem | Out-Null
  # deploy SPA
  - ps: $env:REACT_APP_VERSION=$env:APPVEYOR_BUILD_NUMBER
  - cd ./src/Certes.Spa
  - npm install > nul
  - npm run build > nul
  - cd %APPVEYOR_BUILD_FOLDER%
  - az storage blob upload-batch -d spa -s ./src/Certes.Spa/build/ --no-progress > nul
  # deploy web front end
  - dotnet restore > nul
  - msbuild src/Certes.App/Certes.App.csproj /p:DeployOnBuild=true /p:PublishProfile=certes-app /p:Password=%MSDEPLOY_CERTES_APP_PWD% > nul
  - az webapp deployment slot swap -g certes -n certes-app --slot ci > nul
  # deploy api
  - dotnet restore > nul
  - msbuild src/Certes.Api/Certes.Api.csproj /p:DeployOnBuild=true /p:PublishProfile=certes-api /p:Password=%MSDEPLOY_CERTES_API_PWD% > nul
  - az webapp deployment slot swap -g certes -n certes-api --slot ci > nul

test: off
